//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kerry.K35Syn.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AIR
    {
        public string TO1CITY { get; set; }
        public string TO1CTRY { get; set; }
        public string BY1CARRIER { get; set; }
        public string BY1FLTNO { get; set; }
        public short FLTCHANGE { get; set; }
        public string DVCARR { get; set; }
        public string DVCUSTOMS { get; set; }
        public string INSAMTCURR { get; set; }
        public Nullable<decimal> INSAMT { get; set; }
        public Nullable<decimal> PP_FRT { get; set; }
        public Nullable<decimal> CC_FRT { get; set; }
        public Nullable<decimal> PP_VAL { get; set; }
        public Nullable<decimal> CC_VAL { get; set; }
        public Nullable<decimal> PP_TAX { get; set; }
        public Nullable<decimal> CC_TAX { get; set; }
        public Nullable<decimal> PP_DUEAGT { get; set; }
        public Nullable<decimal> CC_DUEAGT { get; set; }
        public Nullable<decimal> PP_DUECARR { get; set; }
        public Nullable<decimal> CC_DUECARR { get; set; }
        public string CODCURRCODE { get; set; }
        public Nullable<decimal> CODEXRATE { get; set; }
        public Nullable<decimal> CODAMT { get; set; }
        public string CHGCODE { get; set; }
        public Nullable<short> DIVFACTOR { get; set; }
        public Nullable<decimal> TOTJCWGT { get; set; }
        public string DESTCURRCODE { get; set; }
        public Nullable<decimal> DESTEXRATE { get; set; }
        public Nullable<decimal> DESTCHRG { get; set; }
        public string DIM_UT { get; set; }
        public Nullable<int> MANIPCS { get; set; }
        public string MANIPCS_UT { get; set; }
        public Nullable<decimal> MANIWGT { get; set; }
        public string MANIWGT_UT { get; set; }
        public Nullable<decimal> MANIVOL { get; set; }
        public string MANIVOL_UT { get; set; }
        public string MANIDESC1 { get; set; }
        public string MANIDESC2 { get; set; }
        public string MANIDESC3 { get; set; }
        public string MANIRMK { get; set; }
        public string AWBFORMID { get; set; }
        public string SHPR_FRTPRT { get; set; }
        public string SHPR_OTHPRT { get; set; }
        public string CSGN_FRTPRT { get; set; }
        public string CSGN_OTHPRT { get; set; }
        public Nullable<int> ARRPCS { get; set; }
        public string ARRPCS_UT { get; set; }
        public Nullable<decimal> ARRGWGT { get; set; }
        public string ARRGWGT_UT { get; set; }
        public Nullable<decimal> ARRVOL { get; set; }
        public string ARRVOL_UT { get; set; }
        public string CURRCODE { get; set; }
        public Nullable<decimal> EXRATE { get; set; }
        public Nullable<decimal> TOTOTHFC { get; set; }
        public Nullable<decimal> TOTOTHLC { get; set; }
        public Nullable<decimal> CODAMTLC { get; set; }
        public Nullable<decimal> CDF { get; set; }
        public string SETTLEMENT { get; set; }
        public long JOB_UNID { get; set; }
        public Nullable<decimal> TOTTAX { get; set; }
        public Nullable<decimal> MANIWGTDISCOUNT { get; set; }
        public string AIRCRAFTTYPE { get; set; }
        public string SCICODE { get; set; }
        public Nullable<decimal> CONVARRGWGT { get; set; }
        public string CONVARRGWGT_UT { get; set; }
        public Nullable<decimal> CONVARRVOL { get; set; }
        public string CONVARRVOL_UT { get; set; }
        public string PARTYID_GHAGENT { get; set; }
        public string IATACODE { get; set; }
        public string SSR1 { get; set; }
        public string SSR2 { get; set; }
        public string SSR3 { get; set; }
        public string OSI1 { get; set; }
        public string OSI2 { get; set; }
        public string OSI3 { get; set; }
        public string SPH1 { get; set; }
        public string SPH2 { get; set; }
        public string SPH3 { get; set; }
        public string SPH4 { get; set; }
        public string SPH5 { get; set; }
        public string SPH6 { get; set; }
        public string SPH7 { get; set; }
        public string SPH8 { get; set; }
        public string SPH9 { get; set; }
        public string EXRATESOURCE { get; set; }
        public string IATAACNO { get; set; }
        public string AIRCRAFTSERVICETYPE { get; set; }
        public string WGTCHRGSOURCE { get; set; }
        public string ACRNO { get; set; }
        public string ACRPOLCTRY { get; set; }
        public string ACRPOLCITY { get; set; }
        public string ACRPOLNAME { get; set; }
        public string ACRCARRIERID { get; set; }
        public string ACRBY1POLCTRY { get; set; }
        public string ACRBY1POLCITY { get; set; }
        public Nullable<System.DateTime> ACRAWBBLDATE { get; set; }
        public Nullable<decimal> ACRPPFRT { get; set; }
        public Nullable<decimal> ACRCCFRT { get; set; }
        public Nullable<decimal> ACRPPVAL { get; set; }
        public Nullable<decimal> ACRCCVAL { get; set; }
        public Nullable<decimal> ACRPPTAX { get; set; }
        public Nullable<decimal> ACRCCTAX { get; set; }
        public Nullable<decimal> ACRPPDUEAGT { get; set; }
        public Nullable<decimal> ACRCCDUEAGT { get; set; }
        public Nullable<decimal> ACRPPDUECARR { get; set; }
        public Nullable<decimal> ACRCCDUECARR { get; set; }
        public Nullable<decimal> ACRTOTPP { get; set; }
        public Nullable<decimal> ACRTOTCC { get; set; }
        public Nullable<decimal> ACRTOTTAX { get; set; }
        public string ACRSHPRFRTPRT { get; set; }
        public string ACRSHPROTHPRT { get; set; }
        public string ACRCSGNFRTPRT { get; set; }
        public string ACRCSGNOTHPRT { get; set; }
        public string ACRFRTTERM { get; set; }
        public string ACROTHTERM { get; set; }
        public string ACRCHGCODE { get; set; }
        public Nullable<decimal> ACRINSAMT { get; set; }
        public string ACRINSAMTCURR { get; set; }
        public string ACRDVCUSTOMS { get; set; }
        public string ACRDVCARR { get; set; }
    
        public virtual JOB JOB { get; set; }
    }
}
