//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kerry.K35Syn.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class IVJOB
    {
        public long IVHDR_UNID { get; set; }
        public int SNO { get; set; }
        public string DOCNO { get; set; }
        public string BIZTYPE { get; set; }
        public string AWBBL { get; set; }
        public string MAWBNO { get; set; }
        public string LOTNO { get; set; }
        public string JOBNO { get; set; }
        public Nullable<System.DateTime> JOBDATE { get; set; }
        public string SHPTYPE { get; set; }
        public string FLT_VESSEL { get; set; }
        public Nullable<System.DateTime> FV_DATE { get; set; }
        public string ORIGINCITY { get; set; }
        public string ORIGINCTRY { get; set; }
        public string DESTCITY { get; set; }
        public string DESTCTRY { get; set; }
        public string POLCITY { get; set; }
        public string POLCTRY { get; set; }
        public string PODCITY { get; set; }
        public string PODCTRY { get; set; }
        public string COMM { get; set; }
        public Nullable<int> TOTPCS { get; set; }
        public string TOTPCS_UT { get; set; }
        public Nullable<decimal> GROSSWT { get; set; }
        public string GROSSWT_UT { get; set; }
        public Nullable<decimal> CHRGWT { get; set; }
        public string CHRGWT_UT { get; set; }
        public Nullable<decimal> VOLUME { get; set; }
        public string VOLUME_UT { get; set; }
        public string CTNTYPE1 { get; set; }
        public string CTNTYPE2 { get; set; }
        public string CTNTYPE3 { get; set; }
        public string CTNTYPE4 { get; set; }
        public Nullable<short> CTNQTY1 { get; set; }
        public Nullable<short> CTNQTY2 { get; set; }
        public Nullable<short> CTNQTY3 { get; set; }
        public Nullable<short> CTNQTY4 { get; set; }
        public string PARTYID_SHPR { get; set; }
        public string SHPRNAME { get; set; }
        public string PARTYID_CSGN { get; set; }
        public string CSGNNAME { get; set; }
        public Nullable<short> ADJUSTMENT { get; set; }
        public Nullable<short> ADFINYEAR { get; set; }
        public Nullable<short> ADFINPERIOD { get; set; }
        public string SONO { get; set; }
        public string COMMCODE { get; set; }
        public Nullable<long> JOB_UNID { get; set; }
        public Nullable<System.DateTime> ARRECVDATE { get; set; }
        public string ARPAID { get; set; }
        public string OFFSCURR { get; set; }
        public Nullable<decimal> OFFSEXRATE { get; set; }
        public Nullable<decimal> OFFSAMTFC { get; set; }
        public Nullable<decimal> OFFSAMTLC { get; set; }
        public string BOOKINGNO { get; set; }
        public string CONTDESC { get; set; }
        public Nullable<System.DateTime> OFFSETDATE { get; set; }
        public Nullable<decimal> TOTAMTBC { get; set; }
        public Nullable<decimal> TOTAMTLC { get; set; }
        public string MBLNO { get; set; }
        public Nullable<short> RECOGNITION { get; set; }
        public string LOTJOBNO { get; set; }
    
        public virtual IVHDR IVHDR { get; set; }
    }
}
