//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kerry.K35Syn.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOB
    {
        public JOB()
        {
            this.AIRROUTE = new HashSet<AIRROUTE>();
        }
    
        public long UNID { get; set; }
        public Nullable<long> VV_UNID { get; set; }
        public Nullable<long> VVSECOND_UNID { get; set; }
        public string OWNERID { get; set; }
        public string GSHPID { get; set; }
        public string BIZTYPE { get; set; }
        public string BOOKINGNO { get; set; }
        public Nullable<System.DateTime> BOOKINGDATE { get; set; }
        public string SHPNO { get; set; }
        public string CONSOLNO { get; set; }
        public Nullable<long> CONSOLLOT_UNID { get; set; }
        public string JOBNO { get; set; }
        public Nullable<System.DateTime> JOBDATE { get; set; }
        public string PROJECTNO { get; set; }
        public string SHPTYPE { get; set; }
        public string OAGENT { get; set; }
        public string PARTYID_CUST { get; set; }
        public string CUSTNAME { get; set; }
        public string CARRIERID { get; set; }
        public string CARRIERCODE { get; set; }
        public string PARTYID_SHPR { get; set; }
        public string SHPRNAME { get; set; }
        public string PARTYID_CSGN { get; set; }
        public string CSGNNAME { get; set; }
        public string PORCITY { get; set; }
        public string PORCTRY { get; set; }
        public string PORNAME { get; set; }
        public string PORMODE { get; set; }
        public string POLCITY { get; set; }
        public string POLCTRY { get; set; }
        public string POLNAME { get; set; }
        public string VIACITY { get; set; }
        public string VIACTRY { get; set; }
        public string PODCITY { get; set; }
        public string PODCTRY { get; set; }
        public string PODNAME { get; set; }
        public string DESTCITY { get; set; }
        public string DESTCTRY { get; set; }
        public string DESTNAME { get; set; }
        public string DEVRYCITY { get; set; }
        public string DEVRYCTRY { get; set; }
        public string DEVRYNAME { get; set; }
        public Nullable<System.DateTime> FLTDATE { get; set; }
        public string FLTTIME { get; set; }
        public Nullable<int> TOTPCS { get; set; }
        public string TOTPCS_UT { get; set; }
        public Nullable<decimal> TOTGWGT { get; set; }
        public string TOTGWGT_UT { get; set; }
        public Nullable<decimal> TOTCWGT { get; set; }
        public string TOTCWGT_UT { get; set; }
        public Nullable<decimal> VWGT { get; set; }
        public string VWGT_UT { get; set; }
        public Nullable<System.DateTime> AWBBLDATE { get; set; }
        public string ORGID { get; set; }
        public string JOBSTAGECODE { get; set; }
        public string CURRENTSTATUS { get; set; }
        public string CURRENTSTAGE { get; set; }
        public string PROCESSSTATUS { get; set; }
        public string USERHLEVEL { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string UPDATEBY { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public string TIMEZONE { get; set; }
        public Nullable<decimal> TOTVOL { get; set; }
        public string TOTVOL_UT { get; set; }
        public string VOIDBY { get; set; }
        public Nullable<System.DateTime> VOIDDATE { get; set; }
        public Nullable<short> ISBOOKING { get; set; }
        public Nullable<short> ISSHP { get; set; }
        public Nullable<decimal> TOTNWGT { get; set; }
        public string TOTNWGT_UT { get; set; }
        public Nullable<decimal> TOTINNERPCS { get; set; }
        public string TOTINNERPCS_UT { get; set; }
        public Nullable<System.DateTime> CONCLOSEDATE { get; set; }
        public string CONCLOSEBY { get; set; }
        public Nullable<System.DateTime> FINCLOSEDATE { get; set; }
        public string FINCLOSEBY { get; set; }
        public Nullable<System.DateTime> PODATE { get; set; }
        public string POTIME { get; set; }
        public string BOOKINGTIME { get; set; }
        public string CONSOLBKNO { get; set; }
        public string SUREFNO { get; set; }
        public string SPREFNO { get; set; }
        public string VOIDTYPE { get; set; }
        public Nullable<System.DateTime> REVCLOSEDATE { get; set; }
        public string REVCLOSEBY { get; set; }
        public Nullable<System.DateTime> COSTCLOSEDATE { get; set; }
        public string COSTCLOSEBY { get; set; }
        public Nullable<decimal> TOTNVOL { get; set; }
        public Nullable<short> ISCWGTBASENET { get; set; }
        public string JOBTYPE { get; set; }
        public string VIANAME { get; set; }
        public string QUOTENO { get; set; }
        public string QUOTESUBNO { get; set; }
        public Nullable<long> QUOTE_UNID { get; set; }
        public Nullable<System.DateTime> VALIDFROM { get; set; }
        public Nullable<System.DateTime> VALIDTO { get; set; }
        public Nullable<System.DateTime> EFFECTVALIDTO { get; set; }
        public string QUOTETYPE { get; set; }
        public Nullable<System.DateTime> PORETADATE { get; set; }
        public string PORETATIME { get; set; }
        public Nullable<System.DateTime> DEVRYETDDATE { get; set; }
        public string DEVRYETDTIME { get; set; }
        public Nullable<System.DateTime> PORETDDATE { get; set; }
        public string PORETDTIME { get; set; }
        public Nullable<System.DateTime> DEVRYETADATE { get; set; }
        public string DEVRYETATIME { get; set; }
        public string SENDERID { get; set; }
        public Nullable<System.DateTime> POSTDATETOBE { get; set; }
        public Nullable<System.DateTime> CLOSINGDATE { get; set; }
        public Nullable<decimal> TOBASEEXRATE { get; set; }
        public Nullable<decimal> FROMBASEEXRATE { get; set; }
        public Nullable<long> SHIPMENTUNID { get; set; }
        public Nullable<decimal> CONVTOTGWGT { get; set; }
        public string CONVTOTGWGT_UT { get; set; }
        public Nullable<decimal> CONVTOTNWGT { get; set; }
        public string CONVTOTNWGT_UT { get; set; }
        public Nullable<decimal> CONVTOTVOL { get; set; }
        public string CONVTOTVOL_UT { get; set; }
        public Nullable<decimal> CONVTOTNVOL { get; set; }
        public Nullable<System.DateTime> POLETDDATE { get; set; }
        public Nullable<System.DateTime> PODETADATE { get; set; }
        public Nullable<System.DateTime> FINALDESTETADATE { get; set; }
        public Nullable<long> VVTHIRD_UNID { get; set; }
        public Nullable<short> RECOGNITION { get; set; }
        public Nullable<int> POLPORTSNO { get; set; }
        public Nullable<int> PODPORTSNO { get; set; }
        public Nullable<long> POLVVUNID { get; set; }
        public Nullable<long> PODVVUNID { get; set; }
        public string VIAZONE { get; set; }
        public string TSPCITY { get; set; }
        public string TSPCTRY { get; set; }
        public string TSPNAME { get; set; }
        public Nullable<short> ISBTBSHP { get; set; }
        public Nullable<short> ISLOCALJOB { get; set; }
        public Nullable<short> ISHUB { get; set; }
        public string READYCLOSEBY { get; set; }
        public string POLETDTIME { get; set; }
        public string PODETATIME { get; set; }
        public Nullable<System.DateTime> LASTRECDATE { get; set; }
        public string LASTRECTIME { get; set; }
    
        public virtual AIR AIR { get; set; }
        public virtual ICollection<AIRROUTE> AIRROUTE { get; set; }
        public virtual JOBOTHER JOBOTHER { get; set; }
    }
}
