//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kerry.K35Syn.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class K35Entities : DbContext
    {
        public K35Entities()
            : base("name=K35Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TB_AWB> TB_AWB { get; set; }
        public DbSet<TB_BILLING> TB_BILLING { get; set; }
        public DbSet<TB_BILLING_REVENUE_REL> TB_BILLING_REVENUE_REL { get; set; }
        public DbSet<TB_CHARGE_CODE> TB_CHARGE_CODE { get; set; }
        public DbSet<TB_COMPANY> TB_COMPANY { get; set; }
        public DbSet<TB_COST> TB_COST { get; set; }
        public DbSet<TB_CURRENCY> TB_CURRENCY { get; set; }
        public DbSet<TB_JOB> TB_JOB { get; set; }
        public DbSet<TB_JOB_STATION_REL> TB_JOB_STATION_REL { get; set; }
        public DbSet<TB_LOCATION> TB_LOCATION { get; set; }
        public DbSet<TB_REVENUE> TB_REVENUE { get; set; }
        public DbSet<TB_STATION> TB_STATION { get; set; }
    }
}
