//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kerry.K35Syn.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class K3Entities : DbContext
    {
        public K3Entities()
            : base("name=K3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AIR> AIR { get; set; }
        public DbSet<AIRROUTE> AIRROUTE { get; set; }
        public DbSet<COST> COST { get; set; }
        public DbSet<IVDTL> IVDTL { get; set; }
        public DbSet<IVHDR> IVHDR { get; set; }
        public DbSet<JOB> JOB { get; set; }
        public DbSet<REVENUE> REVENUE { get; set; }
        public DbSet<JOBOTHER> JOBOTHER { get; set; }
        public DbSet<IVJOB> IVJOB { get; set; }
    }
}
