//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kerry.K35Syn.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class REVENUE
    {
        public int SNO { get; set; }
        public Nullable<short> SORTORDER { get; set; }
        public string CHRGCODE { get; set; }
        public string CHRGDESC { get; set; }
        public string LOCALDESC { get; set; }
        public Nullable<decimal> RATE { get; set; }
        public Nullable<decimal> QUANTITY { get; set; }
        public string QUANTITYUNIT { get; set; }
        public Nullable<decimal> QUANTITY1 { get; set; }
        public string QUANTITY1UNIT { get; set; }
        public string CURRCODE { get; set; }
        public Nullable<decimal> EXRATE { get; set; }
        public Nullable<decimal> AMTFC { get; set; }
        public Nullable<decimal> AMTLC { get; set; }
        public string PPCC { get; set; }
        public string VAT { get; set; }
        public string CO_PARTYID { get; set; }
        public string BILLING_PARTYID { get; set; }
        public string DUECARRAGT { get; set; }
        public short ISMIN { get; set; }
        public short ISPROGRESSIVE { get; set; }
        public short ISSUPRESS { get; set; }
        public string INVDOCNO { get; set; }
        public short ISOWN { get; set; }
        public string CSIND { get; set; }
        public Nullable<decimal> ACTUALAMTLC { get; set; }
        public Nullable<decimal> ACTUALVATAMTLC { get; set; }
        public string REMARK { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string UPDATEBY { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public string DOCTYPE { get; set; }
        public Nullable<short> ISICA { get; set; }
        public string PROFITCENTRE { get; set; }
        public string COSTCENTRE { get; set; }
        public string TIMEZONE { get; set; }
        public Nullable<short> SHORTPAID { get; set; }
        public long SOURCE_UNID { get; set; }
        public string SOURCETYPE { get; set; }
        public string INVSTS { get; set; }
        public int PARENTSNO { get; set; }
        public string ACTUALCURRCODE { get; set; }
        public Nullable<decimal> ACTUALEXRATE { get; set; }
        public Nullable<decimal> ACTUALAMTBC { get; set; }
        public Nullable<decimal> ACTUALVATAMTBC { get; set; }
        public string APPROVEBY1 { get; set; }
        public Nullable<System.DateTime> APPROVEDATE1 { get; set; }
        public string APPROVEBY2 { get; set; }
        public Nullable<System.DateTime> APPROVEDATE2 { get; set; }
        public Nullable<long> JOB_UNID { get; set; }
        public Nullable<long> BATCHUPDATECHRG_UNID { get; set; }
        public Nullable<short> ISFINCOMMPAID { get; set; }
        public string FINCOMMPAIDBY { get; set; }
        public Nullable<System.DateTime> FINCOMMPAIDDATE { get; set; }
        public Nullable<long> ICAPOST_UNID { get; set; }
        public Nullable<long> FINCOMMPAIDHDR_UNID { get; set; }
        public string PARENTSOURCETYPE { get; set; }
        public string POSTBY { get; set; }
        public Nullable<System.DateTime> POSTDATE { get; set; }
        public string QUANTITYDESC { get; set; }
        public Nullable<long> ORIGINSOURCEUNID { get; set; }
        public string ORIGINSOURCETYPE { get; set; }
        public Nullable<int> ORIGINSNO { get; set; }
        public string CATEGORY { get; set; }
        public string TAXABLE { get; set; }
        public Nullable<short> DECLPARTFRT { get; set; }
        public string PERCENTTYPE { get; set; }
        public Nullable<decimal> VATAMTLC { get; set; }
        public Nullable<short> DATASOURCE { get; set; }
        public string REFNO { get; set; }
        public string ICAREFNO { get; set; }
        public Nullable<short> ISICA2 { get; set; }
        public Nullable<short> ISDISBURSEMENT { get; set; }
        public Nullable<int> SOURCE_SNO { get; set; }
        public string BATCHNO { get; set; }
        public string PASSTHROUGH { get; set; }
        public string UNIQUENO { get; set; }
        public string SOURCEUNIQUENO { get; set; }
        public Nullable<short> ISLOCK { get; set; }
        public Nullable<int> LASTPARENTSNO { get; set; }
        public Nullable<long> IVHDRUNID { get; set; }
        public Nullable<short> ISORGCHRG { get; set; }
        public Nullable<short> ISCOPCHRG { get; set; }
        public Nullable<short> PRINTAN { get; set; }
        public string UNIQUEREFNO { get; set; }
        public string CONTNO { get; set; }
        public string CONTNOLIST { get; set; }
        public string EDIREFNO { get; set; }
        public string INTFSTATUS { get; set; }
        public Nullable<System.DateTime> INTFPOSTDATE { get; set; }
        public string INTFPOSTBY { get; set; }
        public Nullable<short> HASPASSTHROUGH { get; set; }
        public string CRI { get; set; }
        public string ARAP { get; set; }
        public Nullable<long> COMBINEJOBUNID { get; set; }
        public Nullable<int> COMBINESNO { get; set; }
        public string COMBINESOURCETYPE { get; set; }
        public string PAYEEPARTYID { get; set; }
        public Nullable<short> RECOGNITIONYEAR { get; set; }
        public Nullable<short> RECOGNITIONPERIOD { get; set; }
        public Nullable<System.DateTime> RECOGNITIONDATE { get; set; }
        public Nullable<long> RMSOURCEUNID { get; set; }
        public string RMSOURCETYPE { get; set; }
        public Nullable<decimal> BASECHG { get; set; }
        public Nullable<int> COPYFROMSNO { get; set; }
        public Nullable<decimal> VATINCRATE { get; set; }
        public Nullable<decimal> VATINCAMTFC { get; set; }
        public Nullable<decimal> VATINCAMTLC { get; set; }
        public Nullable<long> TARIFFUNID { get; set; }
        public string TARIFFNO { get; set; }
        public Nullable<long> TARIFFJOBUNID { get; set; }
        public Nullable<int> TARIFFSNO { get; set; }
        public string TARIFFFROMTYPE { get; set; }
        public string SOURCEREFNO { get; set; }
        public Nullable<short> ISFROMMASTER { get; set; }
        public Nullable<decimal> VATAMT { get; set; }
        public string SUSADVDOCNO { get; set; }
        public string SUSADVDOCTYPE { get; set; }
        public string SUSADVPAYMENTMODE { get; set; }
        public Nullable<long> SUSADVHDRUNID { get; set; }
        public Nullable<System.DateTime> VALIDFROM { get; set; }
        public Nullable<System.DateTime> VALIDTO { get; set; }
        public Nullable<int> CALSET { get; set; }
        public Nullable<short> ICACONFIRMED { get; set; }
    }
}
