//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kerry.K35Syn.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_AWB
    {
        public int ID { get; set; }
        public int JOB_ID { get; set; }
        public Nullable<int> FLIGHT1_ORIGIN_ID { get; set; }
        public Nullable<int> FLIGHT1_DESTINATION_ID { get; set; }
        public Nullable<int> FLIGHT1_CARRIER_ID { get; set; }
        public Nullable<int> FLIGHT2_DESTINATION_ID { get; set; }
        public Nullable<int> FLIGHT2_CARRIER_ID { get; set; }
        public Nullable<int> FLIGHT3_DESTINATION_ID { get; set; }
        public Nullable<int> FLIGHT3_CARRIER_ID { get; set; }
        public string FLIGHT_NO { get; set; }
        public Nullable<decimal> DECLARED_VALUE_FOR_CARRIAGE { get; set; }
        public Nullable<decimal> DECLARED_VALUE_FOR_CUSTOMS { get; set; }
        public Nullable<decimal> AMOUNT_OF_INSURANCE { get; set; }
        public string HANDLING_INFORMATION { get; set; }
        public Nullable<int> BOOKED_QTY { get; set; }
        public string BOOKED_QTY_UNIT { get; set; }
        public Nullable<decimal> BOOKED_WEIGHT { get; set; }
        public string BOOKED_WEIGHT_UNITS { get; set; }
        public Nullable<decimal> BOOKED_VOLUME { get; set; }
        public string BOOKED_VOLUME_UNITS { get; set; }
        public Nullable<int> RECEIVED_QTY { get; set; }
        public string RECEIVED_QTY_UNIT { get; set; }
        public Nullable<decimal> RECEIVED_WEIGHT { get; set; }
        public string RECEIVED_WEIGHT_UNITS { get; set; }
        public Nullable<decimal> RECEIVED_VOLUME { get; set; }
        public string RECEIVED_VOLUME_UNITS { get; set; }
        public Nullable<int> BILLING_QTY { get; set; }
        public string BILLING_QTY_UNIT { get; set; }
        public Nullable<decimal> BILLING_WEIGHT { get; set; }
        public string BILLING_WEIGHT_UNITS { get; set; }
        public Nullable<decimal> BILLING_VOLUME { get; set; }
        public string BILLING_VOLUME_UNITS { get; set; }
        public string BILLING_CALCULATION_BASIS { get; set; }
        public Nullable<decimal> BILLING_RATE { get; set; }
        public Nullable<decimal> BILLING_SUB_TOTAL { get; set; }
        public Nullable<decimal> GROSS_WEIGHT { get; set; }
        public Nullable<decimal> CHARGEABLE_WEIGHT { get; set; }
        public Nullable<decimal> BILLING_CHARGEABLE_WEIGHT { get; set; }
        public Nullable<int> PALLET_QTY { get; set; }
        public int VOLUME_RATIO { get; set; }
        public string COMMODITY_CODE { get; set; }
        public string COMMODITY_DESCRIPTION { get; set; }
        public string MARKS_AND_NUMBERS { get; set; }
        public string GOODS_DESC { get; set; }
        public string OTHER_CHARGES_DESCRIPTION { get; set; }
        public string WAREHOUSE_CODE { get; set; }
        public Nullable<decimal> FREIGHT_CHARGE_AMOUNT { get; set; }
        public Nullable<decimal> PREPAID_WEIGHT_AMOUNT { get; set; }
        public Nullable<decimal> COLLECT_WEIGHT_AMOUNT { get; set; }
        public Nullable<decimal> PREPAID_VALUATION_AMOUNT { get; set; }
        public Nullable<decimal> COLLECT_VALUATION_AMOUNT { get; set; }
        public Nullable<decimal> PREPAID_TAX_AMOUNT { get; set; }
        public Nullable<decimal> COLLECT_TAX_AMOUNT { get; set; }
        public Nullable<decimal> PREPAID_CHARGES_DUE_TO_AGENT_AMOUNT { get; set; }
        public Nullable<decimal> COLLECT_CHARGES_DUE_TO_AGENT_AMOUNT { get; set; }
        public Nullable<decimal> COLLECT_CHARGES_DUE_TO_CARRIER_AMOUNT { get; set; }
        public Nullable<decimal> PREPAID_CHARGES_DUE_TO_CARRIER_AMOUNT { get; set; }
        public Nullable<decimal> PREPAID_TOTAL_AMOUNT { get; set; }
        public Nullable<decimal> COLLECT_TOTAL_AMOUNT { get; set; }
        public Nullable<System.DateTime> BILL_OF_LADING_ISSUE_DATE { get; set; }
        public string BILL_OF_LADING_PLACE_OF_ISSUE { get; set; }
        public string CARGO_LOADING_INSTRUCTION { get; set; }
        public Nullable<int> GROUND_HANDLING_AGENT_ID { get; set; }
        public string CARRIER_SIGNATURE { get; set; }
        public string DECLARANT_SIGNATURE { get; set; }
        public string SECURITY_CODE { get; set; }
        public string SERVICE_LEVEL { get; set; }
        public string SERVICE_TYPE { get; set; }
        public string ISSUE_BY_NAME { get; set; }
        public Nullable<int> ISSUE_BY_ID { get; set; }
        public string CREATE_BY { get; set; }
        public string ISSUE_CARRIER_NAME_CITY { get; set; }
        public System.DateTime CREATE_TIMESTAMP { get; set; }
        public string UPDATE_BY { get; set; }
        public System.DateTime UPDATE_TIMESTAMP { get; set; }
    
        public virtual TB_COMPANY TB_COMPANY { get; set; }
        public virtual TB_LOCATION TB_LOCATION { get; set; }
        public virtual TB_LOCATION TB_LOCATION1 { get; set; }
        public virtual TB_COMPANY TB_COMPANY1 { get; set; }
        public virtual TB_LOCATION TB_LOCATION2 { get; set; }
        public virtual TB_COMPANY TB_COMPANY2 { get; set; }
        public virtual TB_LOCATION TB_LOCATION3 { get; set; }
        public virtual TB_COMPANY TB_COMPANY3 { get; set; }
        public virtual TB_COMPANY TB_COMPANY4 { get; set; }
        public virtual TB_JOB TB_JOB { get; set; }
    }
}
