//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kerry.K35Syn.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_BILLING_REVENUE_REL
    {
        public int ID { get; set; }
        public int BILLING_ID { get; set; }
        public int REVENUE_ID { get; set; }
        public Nullable<decimal> BILLING_AMOUNT { get; set; }
        public string CREATE_BY { get; set; }
        public System.DateTime CREATE_TIMESTAMP { get; set; }
        public string UPDATE_BY { get; set; }
        public System.DateTime UPDATE_TIMESTAMP { get; set; }
        public string REMARK { get; set; }
    
        public virtual TB_BILLING TB_BILLING { get; set; }
        public virtual TB_REVENUE TB_REVENUE { get; set; }
    }
}
