//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kerry.K35Syn.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CURRENCY
    {
        public TB_CURRENCY()
        {
            this.TB_BILLING = new HashSet<TB_BILLING>();
            this.TB_JOB = new HashSet<TB_JOB>();
            this.TB_STATION = new HashSet<TB_STATION>();
        }
    
        public int ID { get; set; }
        public string CURRENCY_CODE { get; set; }
        public string CURRENCY_DESC { get; set; }
        public string SYMBOL { get; set; }
        public Nullable<int> DECIMAL_PLACE { get; set; }
        public string MILLIONDESC { get; set; }
        public string THOUSANDDESC { get; set; }
        public string HUNDREDDESC { get; set; }
        public string TENDESC { get; set; }
        public string INTDESC { get; set; }
        public string FRACDESC { get; set; }
        public string CREATE_BY { get; set; }
        public System.DateTime CREATE_TIMESTAMP { get; set; }
        public string UPDATE_BY { get; set; }
        public System.DateTime UPDATE_TIMESTAMP { get; set; }
    
        public virtual ICollection<TB_BILLING> TB_BILLING { get; set; }
        public virtual ICollection<TB_JOB> TB_JOB { get; set; }
        public virtual ICollection<TB_STATION> TB_STATION { get; set; }
    }
}
