//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kerry.K35Syn.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CHARGE_CODE
    {
        public TB_CHARGE_CODE()
        {
            this.TB_COST = new HashSet<TB_COST>();
            this.TB_REVENUE = new HashSet<TB_REVENUE>();
        }
    
        public int ID { get; set; }
        public string BIZTYPE { get; set; }
        public string CHARGE_CODE { get; set; }
        public string CHARGE_DESC { get; set; }
        public string CHARGE_DESC_LOCAL { get; set; }
        public string CHARGE_TYPE { get; set; }
        public string VAT_TYPE_AR { get; set; }
        public string AUTO_COST { get; set; }
        public string UNIT { get; set; }
        public string CURR_CODE { get; set; }
        public Nullable<int> PAY_TO { get; set; }
        public string IS_ACTIVE { get; set; }
        public string IS_GLOBAL { get; set; }
        public string IS_GATEWAY_REVENUE { get; set; }
        public Nullable<int> RND_METHOD_CB { get; set; }
        public Nullable<int> DECIMAL_PLACE_CB { get; set; }
        public Nullable<int> RND_METHOD_AMT { get; set; }
        public Nullable<int> DECIMAL_PLACE_AMT { get; set; }
        public string DUE_TO { get; set; }
        public string IS_FREIGHT_RELATED { get; set; }
        public string ALLOCATION { get; set; }
        public string CREATE_BY { get; set; }
        public System.DateTime CREATE_TIMESTAMP { get; set; }
        public string UPDATE_BY { get; set; }
        public System.DateTime UPDATE_TIMESTAMP { get; set; }
        public string VAT_TYPE_AP { get; set; }
    
        public virtual ICollection<TB_COST> TB_COST { get; set; }
        public virtual ICollection<TB_REVENUE> TB_REVENUE { get; set; }
    }
}
