//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kerry.K35Syn.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_COMPANY
    {
        public TB_COMPANY()
        {
            this.TB_AWB = new HashSet<TB_AWB>();
            this.TB_AWB1 = new HashSet<TB_AWB>();
            this.TB_AWB2 = new HashSet<TB_AWB>();
            this.TB_AWB3 = new HashSet<TB_AWB>();
            this.TB_AWB4 = new HashSet<TB_AWB>();
            this.TB_BILLING = new HashSet<TB_BILLING>();
            this.TB_COST = new HashSet<TB_COST>();
            this.TB_JOB = new HashSet<TB_JOB>();
            this.TB_JOB1 = new HashSet<TB_JOB>();
            this.TB_JOB2 = new HashSet<TB_JOB>();
            this.TB_JOB3 = new HashSet<TB_JOB>();
            this.TB_JOB4 = new HashSet<TB_JOB>();
            this.TB_JOB5 = new HashSet<TB_JOB>();
            this.TB_JOB6 = new HashSet<TB_JOB>();
            this.TB_JOB7 = new HashSet<TB_JOB>();
            this.TB_JOB8 = new HashSet<TB_JOB>();
            this.TB_JOB9 = new HashSet<TB_JOB>();
            this.TB_JOB10 = new HashSet<TB_JOB>();
            this.TB_JOB11 = new HashSet<TB_JOB>();
            this.TB_REVENUE = new HashSet<TB_REVENUE>();
            this.TB_STATION = new HashSet<TB_STATION>();
        }
    
        public int ID { get; set; }
        public string LOCATION_CODE { get; set; }
        public string COUNTRY_CODE { get; set; }
        public string COMPANY_CODE { get; set; }
        public string COMPANY_NAME_ENG { get; set; }
        public string COMPANY_NAME_LOCAL { get; set; }
        public string SHORT_NAME { get; set; }
        public string COMPANY_DUPKEY { get; set; }
        public string SALES_USER_CODE { get; set; }
        public string STATUS { get; set; }
        public string LOCAL_CURRENCY { get; set; }
        public string REMARK { get; set; }
        public string IATACODE { get; set; }
        public string IATAACCNO { get; set; }
        public string IATACASSADDR { get; set; }
        public string IATAPARTICIPANT { get; set; }
        public string PIMASENDERID { get; set; }
        public string PIMAADDRESS { get; set; }
        public string SCACCODE { get; set; }
        public string INTTRASENDERID { get; set; }
        public string AMSSENDERID { get; set; }
        public string ACISENDERID { get; set; }
        public string AFRSENDERID { get; set; }
        public Nullable<System.DateTime> LAST_USED_SHP { get; set; }
        public Nullable<System.DateTime> LAST_USED_CSGN { get; set; }
        public Nullable<System.DateTime> LAST_USED_CUST { get; set; }
        public Nullable<System.DateTime> LAST_USED_FNA { get; set; }
        public Nullable<System.DateTime> LAST_USED_AGT { get; set; }
        public Nullable<System.DateTime> LAST_USED_COLOAD { get; set; }
        public string CREATE_BY { get; set; }
        public System.DateTime CREATE_TIMESTAMP { get; set; }
        public string UPDATE_BY { get; set; }
        public System.DateTime UPDATE_TIMESTAMP { get; set; }
        public string AWB_PREFIX { get; set; }
        public string AIRLINE_CODE { get; set; }
    
        public virtual ICollection<TB_AWB> TB_AWB { get; set; }
        public virtual ICollection<TB_AWB> TB_AWB1 { get; set; }
        public virtual ICollection<TB_AWB> TB_AWB2 { get; set; }
        public virtual ICollection<TB_AWB> TB_AWB3 { get; set; }
        public virtual ICollection<TB_AWB> TB_AWB4 { get; set; }
        public virtual ICollection<TB_BILLING> TB_BILLING { get; set; }
        public virtual ICollection<TB_COST> TB_COST { get; set; }
        public virtual ICollection<TB_JOB> TB_JOB { get; set; }
        public virtual ICollection<TB_JOB> TB_JOB1 { get; set; }
        public virtual ICollection<TB_JOB> TB_JOB2 { get; set; }
        public virtual ICollection<TB_JOB> TB_JOB3 { get; set; }
        public virtual ICollection<TB_JOB> TB_JOB4 { get; set; }
        public virtual ICollection<TB_JOB> TB_JOB5 { get; set; }
        public virtual ICollection<TB_JOB> TB_JOB6 { get; set; }
        public virtual ICollection<TB_JOB> TB_JOB7 { get; set; }
        public virtual ICollection<TB_JOB> TB_JOB8 { get; set; }
        public virtual ICollection<TB_JOB> TB_JOB9 { get; set; }
        public virtual ICollection<TB_JOB> TB_JOB10 { get; set; }
        public virtual ICollection<TB_JOB> TB_JOB11 { get; set; }
        public virtual ICollection<TB_REVENUE> TB_REVENUE { get; set; }
        public virtual ICollection<TB_STATION> TB_STATION { get; set; }
    }
}
