//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kerry.K35Syn.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_JOB_STATION_REL
    {
        public int ID { get; set; }
        public int JOB_ID { get; set; }
        public string STATION_CODE { get; set; }
        public string STATION_ROLE { get; set; }
        public string BIZTYPE { get; set; }
        public Nullable<int> SALES_USER_ID { get; set; }
        public Nullable<int> SALES_DEPT_ID { get; set; }
        public Nullable<int> CUSTOMER_SERVICE_USER_ID { get; set; }
        public Nullable<int> CUSTOMER_SERVICE_DEPT_ID { get; set; }
        public Nullable<int> OPERATOR_USER_ID { get; set; }
        public Nullable<int> OPERATOR_DEPT_ID { get; set; }
        public Nullable<int> CUSTOMS_DECLARE_USER_ID { get; set; }
        public Nullable<int> CUSTOMS_DECLARE_DEPT_ID { get; set; }
        public Nullable<int> CUSTOMS_INSPECT_USER_ID { get; set; }
        public Nullable<int> CUSTOMS_INSPECT_DEPT_ID { get; set; }
        public string CREATE_BY { get; set; }
        public System.DateTime CREATE_TIMESTAMP { get; set; }
        public string UPDATE_BY { get; set; }
        public System.DateTime UPDATE_TIMESTAMP { get; set; }
        public int SNO { get; set; }
        public int STATION_ID { get; set; }
        public string STATUS { get; set; }
    
        public virtual TB_JOB TB_JOB { get; set; }
        public virtual TB_STATION TB_STATION { get; set; }
    }
}
