//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kerry.K35Syn.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_JOB
    {
        public TB_JOB()
        {
            this.TB_AWB = new HashSet<TB_AWB>();
            this.TB_BILLING = new HashSet<TB_BILLING>();
            this.TB_COST = new HashSet<TB_COST>();
            this.TB_COST1 = new HashSet<TB_COST>();
            this.TB_JOB1 = new HashSet<TB_JOB>();
            this.TB_JOB_STATION_REL = new HashSet<TB_JOB_STATION_REL>();
            this.TB_REVENUE = new HashSet<TB_REVENUE>();
            this.TB_REVENUE1 = new HashSet<TB_REVENUE>();
        }
    
        public int ID { get; set; }
        public Nullable<int> PARENT_ID { get; set; }
        public string JOB_NO { get; set; }
        public string SHIPMENT_TYPE { get; set; }
        public string SEND_KLN { get; set; }
        public Nullable<int> KLN_JOB_ID { get; set; }
        public string BIZTYPE { get; set; }
        public string OTHER_SERVICE_BIZTYPE { get; set; }
        public string OTHER_SERVICE_SUBTYPE { get; set; }
        public string BOOKING_NO { get; set; }
        public string BOOKING_TYPE { get; set; }
        public string SHIPMENT_NO { get; set; }
        public string HOUSE_NO { get; set; }
        public string GLOBAL_SHIPMENT_ID { get; set; }
        public string MASTER_NO { get; set; }
        public string IS_NO_AWB { get; set; }
        public Nullable<System.DateTime> JOB_DATE { get; set; }
        public string STATION_CODE { get; set; }
        public string SALES_TYPE { get; set; }
        public string COLOAD_TYPE { get; set; }
        public Nullable<int> COLOAD_COMPANY_ID { get; set; }
        public Nullable<int> CUSTOMER_COMPANY_ID { get; set; }
        public Nullable<int> OVERSEAS_AGENT_ID { get; set; }
        public string PROJECT_CODE { get; set; }
        public string INCOTERMS { get; set; }
        public Nullable<decimal> SELLING_RATE { get; set; }
        public Nullable<decimal> BUYING_RATE { get; set; }
        public Nullable<decimal> COMMISSION_RATE { get; set; }
        public string SERVICE_TYPE { get; set; }
        public string SERVICE_LEVEL { get; set; }
        public string HS_CODE { get; set; }
        public string DECLARATION_MODE { get; set; }
        public string TRADE_MODE { get; set; }
        public Nullable<int> OPERATING_PARTY_ID { get; set; }
        public Nullable<System.DateTime> CARGO_READY_DATE { get; set; }
        public Nullable<int> SHIPPER_COMPANY_ID { get; set; }
        public string SHIPPER_NAME { get; set; }
        public string SHIPPER_ADDRESS { get; set; }
        public Nullable<int> CONSIGNEE_COMPANY_ID { get; set; }
        public string CONSIGNEE_NAME { get; set; }
        public string CONSIGNEE_ADDRESS { get; set; }
        public Nullable<int> NOTIFY_COMPANY_ID { get; set; }
        public string NOTIFY_COMPANY_NAME { get; set; }
        public string NOTIFY_COMPANY_ADDRESS { get; set; }
        public Nullable<int> NOTIFY2_COMPANY_ID { get; set; }
        public string NOTIFY2_COMPANY_ADDRESS { get; set; }
        public Nullable<int> LOCAL_AGENT_ID { get; set; }
        public Nullable<int> TRUCKER_ID { get; set; }
        public Nullable<int> DOC_TURNOVER_COMPANY_ID { get; set; }
        public string PAYMENT_INFORMATION_DESCRIPTION { get; set; }
        public Nullable<int> POR_LOCATION_ID { get; set; }
        public Nullable<int> ORIGIN_LOCATION_ID { get; set; }
        public string ORIGIN_LOCATION_CODE { get; set; }
        public string ORIGIN_COUNTRY_CODE { get; set; }
        public string ORIGIN_DESCRIPTION { get; set; }
        public Nullable<int> DESTINATION_LOCATION_ID { get; set; }
        public string DESTINATION_LOCATION_CODE { get; set; }
        public string DESTINATION_COUNTRY_CODE { get; set; }
        public string DESTINATION_DESCRIPTION { get; set; }
        public Nullable<int> MASTER_DESTINATION_ID { get; set; }
        public string MASTER_DESTINATION_LOCATION_CODE { get; set; }
        public string MASTER_DESTINATION_COUNTRY_CODE { get; set; }
        public string MASTER_DESTINATION_DESCRIPTION { get; set; }
        public string ISSUING_AGENT_NAME { get; set; }
        public Nullable<int> GATEWAY_ID { get; set; }
        public string GATEWAY_COUNTRY { get; set; }
        public string GATEWAY_LOCATION { get; set; }
        public Nullable<System.DateTime> ETD_DATE { get; set; }
        public Nullable<System.DateTime> ETA_DATE { get; set; }
        public Nullable<System.DateTime> FINAL_ETA_DATE { get; set; }
        public Nullable<System.DateTime> ATD_DATE { get; set; }
        public Nullable<System.DateTime> ATA_DATE { get; set; }
        public Nullable<System.DateTime> POD_DATE { get; set; }
        public Nullable<int> CURRENCY_ID { get; set; }
        public string FREIGHT_PAYMENT_TYPE { get; set; }
        public string OTHER_CHARGES_PAYMENT_TYPE { get; set; }
        public Nullable<System.DateTime> LAST_LOCKED { get; set; }
        public Nullable<System.DateTime> LAST_UNLOCKED { get; set; }
        public string CREATE_BY { get; set; }
        public System.DateTime CREATE_TIMESTAMP { get; set; }
        public string UPDATE_BY { get; set; }
        public System.DateTime UPDATE_TIMESTAMP { get; set; }
        public string IS_LOCKED { get; set; }
        public string IS_CONSOL_CLOSED { get; set; }
        public string IS_CLOSED { get; set; }
        public string IS_ACTIVE { get; set; }
        public string WAREHOUSE_STATUS { get; set; }
        public string PRE_ALERT_STATUS { get; set; }
        public string REJECT_BY { get; set; }
        public Nullable<System.DateTime> REJECT_TIMESTAMP { get; set; }
        public string CONFIRMED_BY { get; set; }
        public Nullable<System.DateTime> CONFIRMED_TIMESTAMP { get; set; }
        public Nullable<System.DateTime> STOCK_IN_DATE { get; set; }
        public Nullable<System.DateTime> STOCK_OUT_DATE { get; set; }
        public string READY_FOR_STOCK_OUT { get; set; }
        public string IS_PREPARE_LABEL { get; set; }
        public int STATION_ID { get; set; }
        public Nullable<int> THIRD_PARTY_COMPANY_ID { get; set; }
        public string LANE_NO { get; set; }
        public string IS_DG { get; set; }
        public Nullable<int> EVENT_GROUP_ID { get; set; }
        public string EVENT_GROUP_DESCRIPTION { get; set; }
    
        public virtual ICollection<TB_AWB> TB_AWB { get; set; }
        public virtual ICollection<TB_BILLING> TB_BILLING { get; set; }
        public virtual TB_COMPANY TB_COMPANY { get; set; }
        public virtual TB_COMPANY TB_COMPANY1 { get; set; }
        public virtual TB_COMPANY TB_COMPANY2 { get; set; }
        public virtual TB_COMPANY TB_COMPANY3 { get; set; }
        public virtual TB_COMPANY TB_COMPANY4 { get; set; }
        public virtual TB_COMPANY TB_COMPANY5 { get; set; }
        public virtual TB_COMPANY TB_COMPANY6 { get; set; }
        public virtual TB_COMPANY TB_COMPANY7 { get; set; }
        public virtual TB_COMPANY TB_COMPANY8 { get; set; }
        public virtual TB_COMPANY TB_COMPANY9 { get; set; }
        public virtual TB_COMPANY TB_COMPANY10 { get; set; }
        public virtual TB_COMPANY TB_COMPANY11 { get; set; }
        public virtual ICollection<TB_COST> TB_COST { get; set; }
        public virtual ICollection<TB_COST> TB_COST1 { get; set; }
        public virtual TB_CURRENCY TB_CURRENCY { get; set; }
        public virtual TB_LOCATION TB_LOCATION { get; set; }
        public virtual TB_LOCATION TB_LOCATION1 { get; set; }
        public virtual TB_LOCATION TB_LOCATION2 { get; set; }
        public virtual ICollection<TB_JOB> TB_JOB1 { get; set; }
        public virtual TB_JOB TB_JOB2 { get; set; }
        public virtual TB_LOCATION TB_LOCATION3 { get; set; }
        public virtual TB_STATION TB_STATION { get; set; }
        public virtual ICollection<TB_JOB_STATION_REL> TB_JOB_STATION_REL { get; set; }
        public virtual ICollection<TB_REVENUE> TB_REVENUE { get; set; }
        public virtual ICollection<TB_REVENUE> TB_REVENUE1 { get; set; }
    }
}
