//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kerry.K35Syn.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_LOCATION
    {
        public TB_LOCATION()
        {
            this.TB_AWB = new HashSet<TB_AWB>();
            this.TB_AWB1 = new HashSet<TB_AWB>();
            this.TB_AWB2 = new HashSet<TB_AWB>();
            this.TB_AWB3 = new HashSet<TB_AWB>();
            this.TB_JOB = new HashSet<TB_JOB>();
            this.TB_JOB1 = new HashSet<TB_JOB>();
            this.TB_JOB2 = new HashSet<TB_JOB>();
            this.TB_JOB3 = new HashSet<TB_JOB>();
            this.TB_STATION = new HashSet<TB_STATION>();
            this.TB_STATION1 = new HashSet<TB_STATION>();
        }
    
        public int ID { get; set; }
        public string LOCATION_CODE { get; set; }
        public string COUNTRY_CODE { get; set; }
        public string UNLOC_CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public string IATA_DESCRIPTION { get; set; }
        public string IS_AIR_LOCATION { get; set; }
        public string IS_SEA_LOCATION { get; set; }
        public string TIMEZONE { get; set; }
        public string IS_ACTIVE { get; set; }
        public string CREATE_BY { get; set; }
        public System.DateTime CREATE_TIMESTAMP { get; set; }
        public string UPDATE_BY { get; set; }
        public System.DateTime UPDATE_TIMESTAMP { get; set; }
    
        public virtual ICollection<TB_AWB> TB_AWB { get; set; }
        public virtual ICollection<TB_AWB> TB_AWB1 { get; set; }
        public virtual ICollection<TB_AWB> TB_AWB2 { get; set; }
        public virtual ICollection<TB_AWB> TB_AWB3 { get; set; }
        public virtual ICollection<TB_JOB> TB_JOB { get; set; }
        public virtual ICollection<TB_JOB> TB_JOB1 { get; set; }
        public virtual ICollection<TB_JOB> TB_JOB2 { get; set; }
        public virtual ICollection<TB_JOB> TB_JOB3 { get; set; }
        public virtual ICollection<TB_STATION> TB_STATION { get; set; }
        public virtual ICollection<TB_STATION> TB_STATION1 { get; set; }
    }
}
