//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kerry.K35Syn.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_STATION
    {
        public TB_STATION()
        {
            this.TB_BILLING = new HashSet<TB_BILLING>();
            this.TB_COST = new HashSet<TB_COST>();
            this.TB_JOB = new HashSet<TB_JOB>();
            this.TB_JOB_STATION_REL = new HashSet<TB_JOB_STATION_REL>();
            this.TB_STATION1 = new HashSet<TB_STATION>();
        }
    
        public int ID { get; set; }
        public string STATION_LEVEL { get; set; }
        public string STATION_TYPE { get; set; }
        public string STATION_CODE { get; set; }
        public string STATION_NAME_ENG { get; set; }
        public string STATION_NAME_LOCAL { get; set; }
        public Nullable<int> COMPANY_ID { get; set; }
        public string HIERARCHY { get; set; }
        public Nullable<int> KLN_STATION_ID { get; set; }
        public Nullable<int> SEAPORT_ID { get; set; }
        public Nullable<int> AIRPORT_ID { get; set; }
        public Nullable<int> CURRENCY_ID { get; set; }
        public string CURRENCY_CODE { get; set; }
        public string WEIGHT_UOM { get; set; }
        public string VOLUME_UOM { get; set; }
        public string CREATE_BY { get; set; }
        public System.DateTime CREATE_TIMESTAMP { get; set; }
        public string UPDATE_BY { get; set; }
        public System.DateTime UPDATE_TIMESTAMP { get; set; }
        public Nullable<decimal> TOLERENCE { get; set; }
        public Nullable<decimal> TOLERENCE_AMT { get; set; }
    
        public virtual ICollection<TB_BILLING> TB_BILLING { get; set; }
        public virtual TB_COMPANY TB_COMPANY { get; set; }
        public virtual ICollection<TB_COST> TB_COST { get; set; }
        public virtual TB_CURRENCY TB_CURRENCY { get; set; }
        public virtual ICollection<TB_JOB> TB_JOB { get; set; }
        public virtual ICollection<TB_JOB_STATION_REL> TB_JOB_STATION_REL { get; set; }
        public virtual TB_LOCATION TB_LOCATION { get; set; }
        public virtual TB_LOCATION TB_LOCATION1 { get; set; }
        public virtual ICollection<TB_STATION> TB_STATION1 { get; set; }
        public virtual TB_STATION TB_STATION2 { get; set; }
    }
}
